name: Docker Image Deployment to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_IMAGE_NAME: 'github-actions-docker-demo'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and push
      run: |
        docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'
        docker build . --file Dockerfile --tag '${{secrets.DOCKER_LOGIN}}'/'${{env.DOCKER_IMAGE_NAME}}':${{ github.sha }}
        docker push '${{secrets.DOCKER_LOGIN}}'/'${{env.DOCKER_IMAGE_NAME}}':${{ github.sha }}
        docker scan --login --token ${{ secrets.SNYK_TOKEN }}
        docker scan my_docker_image:$(date +%s)
